from . import views
from django.urls import path


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('employees/', views.EmployeesList.as_view(), name='Listofemployees'),
    path('employee/<int:pk>/', views.EnployeeDetailView.as_view(),
         name='Detailofemployees'),
    path('employee/new/', views.EnployeeAddView.as_view(),
         name='Addanemployees'),
    path('employee/<int:pk>/modify/', views.ModifyEmployeeView.as_view(),
         name='modify_employee'),
    path('employee/<int:pk>/delete/', views.DeleteEmployeeView.as_view(),
         name='delete_employee'),
    path('years/', views.YearList.as_view(),
         name='Yearview'),
    path('year/<int:pk>/', views.YearDetailView.as_view(),
         name='Detailofyears'),
    path('year/new/', views.YearAddView.as_view(),
         name='Addayear'),
    path('year/<int:pk>/modify/', views.ModifyYearView.as_view(),
         name='modify_year'),
    path('year/<int:pk>/delete/', views.DeleteYearView.as_view(),
         name='delete_year'),
    path('generator/', views.GeneratorYearView.as_view(), name='generator_year'),
    path('generator/<int:year>/',
         views.GeneratorMonthView.as_view(), name='generator_month'),
    path('generator/<int:year>/<int:month>/employees/',
         views.GeneratorEmployeesView.as_view(), name='generator_employees'),
    path('generator/<int:year>/<int:month>/monthly-table/',
         views.GeneratorMonthlyTableView.as_view(), name='generator_monthly_table'),
    path('generator/<int:year>/<str:month>/monthly-table/save/',
         views.GeneratorSaveMonthlyTableView.as_view(), name='generator_save_monthly_table'),
    path('generator/<int:year>/<str:month>/monthly-table/delete/',
         views.GeneratorDeleteMonthlyDataView.as_view(), name='generator_delete_monthly_data'),
    path('generator/<int:year>/<str:month>/see/',
         views.GeneratorSeeView.as_view(), name='generator_see'),
    path('generator/<int:year>/<str:month>/pay/',
         views.GeneratorPayView.as_view(), name='generator_pay'),
    path('generator/<int:year>/<str:month>/reopen/',
         views.GeneratorReopenView.as_view(), name='generator_reopen'),
    path('overview/', views.OverviewYearView.as_view(), name='overview'),
    path('overview/export/', views.OverviewExportView.as_view(),
         name='overview_export'),
]
