# Generated by Django 3.2.22 on 2023-10-31 07:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salary_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avs_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ac_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ac2_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('laap_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('laanp_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('laac_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('laace_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amat_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alfa_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('apgmal_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alpetiteenfance_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expense_report', models.DecimalField(decimal_places=2, max_digits=5)),
                ('public_transportation_fees', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employees_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('employees_marital_status', models.CharField(choices=[('M', 'Married'), ('D', 'Divorced'), ('S', 'Single'), ('P', 'Partnership'), ('O', 'Other')], max_length=1)),
                ('children_for_allocations_type_1', models.IntegerField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5), ('SIX', 6), ('SEVEN', 7), ('EIGHT', 8), ('NINE', 9), ('THEN', 10)])),
                ('children_for_allocations_type_2', models.IntegerField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5), ('SIX', 6), ('SEVEN', 7), ('EIGHT', 8), ('NINE', 9), ('THEN', 10)])),
                ('birth_date', models.DateField()),
                ('employees_age', models.PositiveSmallIntegerField()),
                ('email_adress', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('emergency_contact', models.CharField(max_length=30)),
                ('emergency_phonenumber', models.IntegerField()),
                ('employee_picture', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('social_security_number', models.CharField(max_length=13, unique=True)),
                ('employees_bankaccount', models.CharField(max_length=21)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employees_holiday_rights', models.IntegerField()),
                ('base_monthly_salary', models.IntegerField()),
                ('employees_phone_allocation', models.PositiveSmallIntegerField()),
                ('employees_representation_allocation', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('seniority', models.DurationField()),
                ('employees_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
