# Generated by Django 3.2.22 on 2024-10-12 20:55

from django.db import migrations, models
import hrmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birth_date',
            field=models.DateField(default='1900-01-01', validators=[hrmanager.validators.validate_birth_date_in_past, hrmanager.validators.validate_date_format, hrmanager.validators.validate_not_blank_nor_null]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employees_age',
            field=models.PositiveSmallIntegerField(default='0', validators=[hrmanager.validators.validate_not_blank_nor_null]),
        ),
    ]
