# Generated by Django 3.2.22 on 2023-11-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='children_for_allocations_type_1',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='children_for_allocations_type_2',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
