# Generated by Django 3.2.22 on 2024-10-13 06:06

import django.core.validators
from django.db import migrations, models
import hrmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0004_alter_employees_email_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email_adress',
            field=models.EmailField(default='noneemail@noneemail.com', error_messages={'unique': 'An employee with this email address already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), hrmanager.validators.validate_not_blank_nor_null]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='end_date',
            field=models.DateField(blank=True, default='None', null=True),
        ),
    ]
