# Generated by Django 3.2.22 on 2024-10-14 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0005_auto_20241013_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency_phonenumber',
            field=models.CharField(blank=True, help_text='Format: 0041/00.000.00.00', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 00041/00.000.00.00', regex='^0041/\\d{2}\\.\\d{3}\\.\\d{2}\\.\\d{2}$')]),
        ),
    ]
