# Generated by Django 3.2.22 on 2024-10-14 19:47

import django.core.validators
from django.db import migrations, models
import hrmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0006_alter_employees_emergency_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 0041/00.000.00.00', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 00041/00.000.00.00', regex='^0041/\\d{2}\\.\\d{3}\\.\\d{2}\\.\\d{2}$'), hrmanager.validators.validate_not_blank_nor_null]),
        ),
    ]
