# Generated by Django 3.2.22 on 2024-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0007_alter_employees_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employees_phone_allocation',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employees_representation_allocation',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
