# Generated by Django 3.2.23 on 2023-11-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0007_auto_20231121_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_year', models.IntegerField()),
                ('gd_month', models.CharField(max_length=20)),
                ('gd_title', models.CharField(max_length=255)),
                ('gd_first_name', models.CharField(max_length=255)),
                ('gd_last_name', models.CharField(max_length=255)),
                ('gd_base_monthly_salary', models.IntegerField()),
                ('gd_child_allocation_1', models.IntegerField()),
                ('gd_child_allocation_2', models.IntegerField()),
                ('gd_total_monthly_wage', models.IntegerField()),
                ('gd_total_monthly_wage_for_social_insurance', models.IntegerField()),
                ('gd_total_monthly_wage_for_social_taxes', models.IntegerField()),
                ('gd_avs_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_ac_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_ac2_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_laap_item', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gd_laanp_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_laac_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_laace_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_amat_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_alfa_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_apgmal_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_alpetiteenfance_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_total_social_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_employees_phone_allocation', models.PositiveSmallIntegerField()),
                ('gd_employees_representation_allocation', models.PositiveSmallIntegerField()),
                ('gd_expense_report', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_public_transportation_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gd_paid_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
