# Generated by Django 3.2.22 on 2024-10-16 18:52

from django.db import migrations, models
import hrmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0008_auto_20241016_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employees_phone_allocation',
            field=models.PositiveSmallIntegerField(default=0, validators=[hrmanager.validators.validate_not_blank_nor_null]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employees_representation_allocation',
            field=models.PositiveSmallIntegerField(default=0, validators=[hrmanager.validators.validate_not_blank_nor_null]),
        ),
    ]
