# Generated by Django 3.2.23 on 2023-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0009_auto_20231123_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_items',
            name='expense_report',
        ),
        migrations.RemoveField(
            model_name='salary_items',
            name='public_transportation_fees',
        ),
        migrations.AddField(
            model_name='employees',
            name='LPP_deduction_employee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='LPP_deduction_employer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='expense_report',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='public_transportation_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_calculated_monthly_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_first_day_of_the_month_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_last_day_of_the_month_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_worked_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employees_phone_allocation',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employees_representation_allocation',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_ac2_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_ac_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_alfa_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_alpetiteenfance_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_amat_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_apgmal_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_avs_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_employees_phone_allocation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_employees_representation_allocation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_expense_report',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_laac_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_laace_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_laanp_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_laap_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_paid_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_public_transportation_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_total_social_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
