# Generated by Django 3.2.23 on 2023-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0010_auto_20231124_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='extraordinary_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salary_items',
            name='child_alloc_1_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salary_items',
            name='child_alloc_2_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
