# Generated by Django 3.2.23 on 2023-11-28 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0012_auto_20231125_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatordata',
            name='gd_calculated_monthly_salary',
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_LPP_deduction_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_correction_non_financial_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_extraordinary_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatordata',
            name='gd_total_deduction_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_monthly_table_paid',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_monthly_table_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_total_monthly_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_total_monthly_wage_for_social_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generatordata',
            name='gd_total_monthly_wage_for_social_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
