# Generated by Django 3.2.22 on 2023-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0014_auto_20231208_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='seniority',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
